services:
  backend:
    build: ./backend        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    image: 505093077290.dkr.ecr.us-east-1.amazonaws.com/cassiecodes-backend:latest

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    image: 505093077290.dkr.ecr.us-east-1.amazonaws.com/cassiecodes-frontend:latest