name: Build and Deploy Docker Images to Amazon ECR

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Frontend
      id: build-frontend
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        echo "Retrieving ECR token"
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
        # Build a docker container and push it to ECR 
        echo "Building docker image"
        docker build -t cassiecodes-frontend .
        echo "Tagging image"
        docker tag cassiecodes-frontend:latest $ECR_REGISTRY/cassiecodes-frontend:latest
        echo "Pushing frontend to ECR..."
        docker push $ECR_REGISTRY/cassiecodes-frontend:latest
        echo "Done."
      working-directory: ./frontend

    - name: Build and Push Backend
      id: build-backend
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        echo "Retrieving ECR token"
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
        # Build a docker container and push it to ECR 
        echo "Building backend docker image"
        docker build -t cassiecodes-backend .
        echo "Tagging backend image"
        docker tag cassiecodes-backend:latest $ECR_REGISTRY/cassiecodes-backend:latest
        echo "Pushing backend to ECR..."
        docker push $ECR_REGISTRY/cassiecodes-backend:latest
        echo "Done."
      working-directory: ./backend
