name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   # need checkout before using compose-action
  #   - uses: actions/checkout@v3
  #   - uses: isbang/compose-action@v1.5.1
  #     with:
  #       compose-file: ".docker-compose.yml"
  #       down-flags: "--volumes"
  #       services: |
  #         backend
  #         frontend
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Frontend
      id: build-image
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        # Build a docker container and push it to ECR 
        docker build -t cassiecodes-frontend .
        echo "Pushing frontend to ECR..."
        docker push $ECR_REGISTRY/cassiecodes-frontend:latest
        echo "Done."
      working-directory: ./frontend
